#let openning(
  title: "",
) = {

  set page(
    margin: (left: 30mm, right: 30mm, top: 40mm, bottom: 40mm),
    numbering: none,
    number-align: center,
  )

  let body-font = "EB Garamond"
  let sans-font = "New Computer Modern Sans"

  set text(
    font: body-font, 
    size: 12pt, 
    lang: "en"
  )

  set par(leading: 1em)

  
  // --- Disclaimer ---
  figure(
    image("../figures/cube.png"),
    caption: title + " (generated by DALL-E)",
    numbering: none
  )
  v(1cm)
  text[
    There have always been ghosts in the machine. Random segments of code, that have grouped together to form unexpected protocols. Unanticipated, these free radicals engender questions of free will, creativity, and even the nature of what we might call the soul. #h(1fr) (I, Robot)
  ]
}
